spring:
   application:
      name: tomp-ref
server:
   port: 8080
tomp:
   lookup-service: http://localhost:7999/
   accept-language: nl
   api-version: 0.4.0
   asset-class: org.tomp.api.operatorinformation.assets.AssetsFromFileProvider
   asset-file: src/main/resources/assets.json
logging:
  level:
    org.springframework: ERROR
    
---
spring: 
   profiles: bike
   application:
      name: bike-to
server: 
   port: 8082
tomp:
   maas-id: 3
   asset-file: src/main/resources/bikes.json
   
---
spring: 
   profiles: bus
   application:
      name: bus-to
server: 
   port: 8086
tomp:
   maas-id: 4

---
spring: 
   profiles: car
   application:
      name: car-to
server: 
   port: 8083
tomp:
   maas-id: 5
   asset-file: src/main/resources/cars.json

---
spring: 
   profiles: train
   application:
      name: train-to
server: 
   port: 8084
tomp:
   maas-id: 6
 
---
spring: 
   profiles: scooter
   application:
      name: scooter-to
server: 
   port: 8085
tomp:
   maas-id: 7

---
spring: 
   profiles: maasprovider
   application:
      name: maasprovider
server: 
   port: 8090
tomp:
   maas-id: 1   
   transport-operators:
     - name: bike
       tomp-api-url: http://localhost:8082
     - name: car
       tomp-api-url: http://localhost:8083

   