import { Address } from './address.model';
import { Customer } from './customer.model';

/**
 * A new booking, created by MaaS POST request in 'PENDING' state.
 * The ID is generated by the TO in the 'availability-check'.
 * The fromAddress, toAddress and the personal data should only be provided if there is an actual request for it (see conditions)
 */
export class BookingOption {
  /**
   * unique ID (TO's perspective) for identifying this specific available (type of) asset
   */
  id: string = '';
  customer: Customer = new Customer();
  fromAddress?: Address = new Address();
  toAddress?: Address = new Address();
}
