spring:
   profiles: parking
   application:
      name: parking
server:
   port: 8069
tomp:
   maas-id: aac7f6ae-1d0d-44cd-9da5-ca62d48eb483
   asset-file: src/main/resources/cars.json
   lookup-service: http://localhost:7999/
   accept-language: nl
   api-version: 0.9.0
   allowUnknownOperators: true
   authenticationRequired: false
   
   system-information-file: src/main/resources/system-info-generic.json
   condition-file: src/main/resources/conditions.json
   regions-file: src/main/resources/regions.json
   stations-file: src/main/resources/stations.json
   area-file: src/main/resources/area.json
   external-url: http://localhost:8069/
   version-file: src/main/resources/versions.json
   providers:
     booking: none
     operatorinformation: parking
     planning: none
     tripexecution: none
parking:
   opendataUrl: https://npropendata.rdw.nl/parkingdata/v2/
   uuids: 
   nameContains: Amsterdam
   refreshInMillis: 60000
   r: 0.00001
logging:
   level:
      org.springframework: ERROR