spring:
   profiles: osm-parking
   application:
      name: osm-parking
server:
   port: 8072
tomp:
   maas-id: a35dba1f-22c1-4080-8556-f3fb23454f80
   lookup-service: http://localhost:7999/
   refreshOnStartUp: false
   allowUnknownOperators: true
   authenticationRequired: false
   accept-language: nl
   api-version: 0.9.0
   area-file: src/main/resources/area.json
   providers:
      operatorinformation: overpass
      booking: none
      planning: none
      tripexecution: none
overpass:
   ql: '"amenity"="parking"'
logging:
   level:
      org.springframework: ERROR