spring:
   profiles: bike
   application:
      name: bike-to
server:
   port: 8082
tomp:
   maas-id: d52bfad0-ee4b-4f72-9f38-efce115ffb49
   lookup-service: http://localhost:7999/
   accept-language: nl
   api-version: 1.0.0
   allowUnknownOperators: true
   authenticationRequired: false

   version-file: src/main/resources/versions.json
   
   system-information-file: src/main/resources/system-info-generic.json
   regions-file: src/main/resources/regions.json
   stations-file: src/main/resources/stations.json
   area-file: src/main/resources/area.json

   asset-file: src/main/resources/bikes.json
   condition-file: src/main/resources/conditions.json

   external-url: http://localhost:8082/
   expiration-days: 14
   currency-code: NL
   vat-rate: 21
   providers:
      operatorinformation: bike
      planning: bike
geodecode:
   active: false
   decodeUrl: https://locationiq.org/v1/reverse.php?key=[some token]&format=json
   streetAddress: address.road| |address.house_number
   area: address.city| - |address.state
   postalCode: address.postcode
   country: address.country
   lon: lon
   lat: lat  
logging:
   level:
      org.springframework: ERROR      