spring:
   profiles: gbfsstar
   application:
      name: gbfsstar
server:
   port: 8071
tomp:
   maas-id: a35dba1f-22c1-4080-8556-f3fb28254f80
   lookup-service: http://localhost:7999/
   refreshOnStartUp: false
   allowUnknownOperators: true
   authenticationRequired: false
   accept-language: nl
   api-version: 0.6.0
   condition-file: src/main/resources/conditions.json
   version-file: src/main/resources/versions.json
   providers:
      operatorinformation: gbfs
      booking: none
      planning: nearStart
      tripexecution: none
gbfs:
   opendataUrl: https://eu.ftp.opendatasoft.com/star/gbfs/gbfs.json
   refreshInMillis: 60000
   r: 1.0E-5
geodecode:
   active: true
   encodeUrl: https://locationiq.org/v1/search.php?key=[key]&format=json&q=
   decodeUrl: https://locationiq.org/v1/reverse.php?key=[key]&format=json
   streetAddress: address.road| |address.house_number
   area: address.city| - |address.state
   postalCode: address.postcode
   country: address.country
   lon: lon
   lat: lat
logging:
   level:
      org.springframework: ERROR