spring:
   profiles: bike
   application:
      name: bike-to
server:
   port: 8082
tomp:
   maas-id: da612986-3408-4c91-adf9-8dbbc16ff4f9
   asset-file: src/main/resources/bikes.json
   lookup-service: http://localhost:7999/
   accept-language: nl
   api-version: 0.5.0
   system-information-file: src/main/resources/system-info-generic.json
   condition-file: src/main/resources/conditions.json
   regions-file: src/main/resources/regions.json
   stations-file: src/main/resources/stations.json
   area-file: src/main/resources/area.json
   external-url: http://localhost:8080/
logging:
   level:
      org.springframework: ERROR      